sonar.projectKey=marimsz_Projeto-VendeAi
sonar.organization=marimsz

sonar.sources=backend/src,frontend

sonar.exclusions=**/node_modules/**,**/dist/**,.next/**

sonar.tests=backend

sonar.test.inclusions=**/*.spec.ts

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info